; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200 ; added for serial monitor


lib_deps = bodmer/TFT_eSPI@^2.5.43 ; this ads in the library needed for the display

; setup pins for the display
build_flags =
    -DUSER_SETUP_LOADED=1 ; this is on (1=true) so that my following setup will be used
    -DILI9341_DRIVER=1 ; this loads the correct driver for my chip
    -DTFT_MISO=-1 ; Define (D) constant called TFT_Master In, Slave Out (-1 for not used since i do not use touch function)
    -DTFT_MOSI=23 ; Master Out, Slave In
    -DTFT_SCLK=18 ; Serial Clock
    -DTFT_CS=16 ; Chip Select
    -DTFT_DC=17 ; Data Command
    -DTFT_RST=4 ; Reset
    -DTFT_BL=19 ; Back Light
    -DSPI_FREQUENCY=40000000 ;40 MHz (for the SPI clock) (safe starting value)
    -DTFT_WIDTH=240 ; width resolution (shorter side)
    -DTFT_HEIGHT=320 ; height resolution (longer side)
    -DLOAD_GLCD=1 ; need fonts for display text to work
